language: php

dist: precise


php:
  - '7.0'
  - hhvm

matrix:
  allow_failures:
    - php: hhvm


addons:
  mariadb: '10.0'


mysql:
  database: travis_ci_drupal
  username: root
  encoding: utf8


install:
  - composer install

before_script:
  - mysql -u root < tests/sql/test.sql

script: phpunit --configuration phpunit_mysql.xml
